version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  wildfly:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
